name: skimage-dev
channels:
  - conda-forge
dependencies:
  # base
  - numpy>=1.24
  - scipy>=1.11.4
  - networkx>=3.0
  - pillow>=10.1
  - imageio>=2.33,!=2.35.0
  - tifffile>=2022.8.12
  - packaging>=21
  - lazy-loader>=0.4
  # build
  - meson-python>=0.16
  - ninja>=1.11.1.1
  - Cython>=3.0.8,!=3.2.0b1
  - pythran>=0.16
  - numpy>=2.0
  - spin==0.13
  - python-build>=1.2.1
  # data
  - pooch>=1.6.0
  # developer
  - pre-commit
  - ipython
  - docstub>=0.6.0,<0.7.0
  # asv
  - asv
  # docs
  - sphinx>=8.0
  - sphinx-gallery>=0.18
  - numpydoc>=1.7
  - sphinx-copybutton
  - matplotlib-base>=3.7
  - dask>=2023.2.0
  - pandas>=2.0
  - seaborn>=0.11
  - pooch>=1.6
  - tifffile>=2022.8.12
  - myst-parser
  - intersphinx-registry>=0.2411.14
  - ipywidgets
  - ipykernel
  - plotly>=5.20
  - python-kaleido==0.2.1
  - scikit-learn>=1.2
  - sphinx-design>=0.5
  - pydata-sphinx-theme>=0.16
  - PyWavelets>=1.6
  - pytest-doctestplus>=1.6.0
  # optional
  - SimpleITK
  - scikit-learn>=1.2
  - pyamg>=5.2
  # optional_free_threaded
  - astropy-base>=6.0
  - dask>=2023.2.0
  - matplotlib-base>=3.7
  - pooch>=1.6.0
  - PyWavelets>=1.6
  # test
  - numpydoc>=1.7
  - pooch>=1.6.0
  - pytest>=8.3
  - pytest-cov>=2.11.0
  - pytest-pretty
  - pytest-localserver
  - pytest-faulthandler
  - pytest-doctestplus>=1.6.0
