version: 2

jobs:
  doc:
    docker:
      - image: circleci/python:3.9.0
    steps:
      - checkout
      - run:
          name: install dependencies and package
          command: |
              python -m venv skimage_venv
              source skimage_venv/bin/activate
              python -m pip install --upgrade pip
              python -m pip install -r requirements/build.txt
              python -m pip install -e . -vv
              python -m pip install -r requirements/default.txt
              python -m pip install -r requirements/docs.txt
              export
      - run:
          name: build doc
          no_output_timeout: 50m
          command: |
              source skimage_venv/bin/activate
              cd doc
              make clean
              make html
      - store_artifacts:
          path: doc/build/html
          destination: doc/build/html

workflows:
  version: 2
  build-doc:
    jobs:
      - doc
