version: 2

jobs:
  doc:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: concatenate requirement files
          command: cat requirements/*.txt > requirements/all_requirements
      - restore_cache:
          keys:
            - data-v1-{{ checksum "skimage/data/_registry.py" }}
      - restore_cache:
          keys:
            - packages-v1-{{ checksum "requirements/all_requirements" }}
      - run:
          name: install dependencies and package
          command: |
            python -m venv skimage_venv
            source skimage_venv/bin/activate
            python -m pip install --upgrade pip
            python -m pip install -r requirements/build.txt
            python -m pip install -e . -vv
            python -m pip install -r requirements/default.txt
            python -m pip install -r requirements/docs.txt
            export
      - save_cache:
          key: packages-v1-{{ checksum "requirements/all_requirements" }}
          paths:
            - skimage_venv
      - run:
          name: build doc
          no_output_timeout: 50m
          command: |
            source skimage_venv/bin/activate
            cd doc
            make clean
            SPHINXOPTS="-j 1" make html
      - save_cache:
          key: data-v1-{{ checksum "skimage/data/_registry.py" }}
          paths:
            - /home/circleci/.cache/scikit-image/master
      - store_artifacts:
          path: doc/build/html

workflows:
  version: 2
  build-doc:
    jobs:
      - doc
