on: [status]
jobs:
  circleci_artifacts_redirector_job:
    runs-on: ubuntu-22.04
    name: Run CircleCI artifacts redirector
    steps:
      - name: GitHub Action step
        id: step1
        uses: larsoner/circleci-artifacts-redirector-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-path: 0/doc/build/html/index.html
          circleci-jobs: doc
          job-title: Check the rendered docs here!
      - name: Check the URL
        run: |
          curl --fail ${{ steps.step1.outputs.url }} | grep $GITHUB_SHA
